_schema: _schema
paths:
  uploads: uploads
  static: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  posts:
    path: _posts
    glob:
    name:
    singular_name:
    icon: notes
    output: true
    url:
    filter:
    parse_branch_index:
    documentation:
    description: ''
    preview:
    sort:
    sort_options:
    singular_key:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
collections_config_override: true
collection_groups:
  - heading: posts
    collections:
      - posts
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_snippets:
  _cc_jekyll_unknown_paired_tag:
    hidden: true
    snippet: >-
      {%[[trim_top_left]] [[name]][[args]]
      [[trim_top_right]]%}[[content]]{%[[trim_bottom_left]] end[[name]]
      [[trim_bottom_right]]%}
    preview:
      text: Unknown Shortcode
      subtext:
        - key: name
      icon: question_mark
    _inputs:
      name:
        type: auto
        hidden: true
        cascade: true
      args:
        type: auto
        hidden: true
        cascade: true
      content:
        type: auto
        hidden: true
        cascade: true
      trim_top_left:
        type: auto
        hidden: true
        cascade: true
      trim_top_right:
        type: auto
        hidden: true
        cascade: true
      trim_bottom_left:
        type: auto
        hidden: true
        cascade: true
      trim_bottom_right:
        type: auto
        hidden: true
        cascade: true
    params:
      content:
        parser: content
        options:
          editor_key: content
      name:
        parser: argument
        options:
          model:
            editor_key: name
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
      args:
        parser: content
        options:
          editor_key: args
          raw: true
          allow_nested: false
      trim_top_left:
        parser: argument
        options:
          model:
            editor_key: trim_top_left
            implied_boolean: true
            allowed_values:
              - '-'
            optional: true
            default: '-'
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
      trim_top_right:
        parser: argument
        options:
          model:
            editor_key: trim_top_right
            implied_boolean: true
            allowed_values:
              - '-'
            optional: true
            default: '-'
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
      trim_bottom_left:
        parser: argument
        options:
          model:
            editor_key: trim_bottom_left
            implied_boolean: true
            allowed_values:
              - '-'
            optional: true
            default: '-'
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
      trim_bottom_right:
        parser: argument
        options:
          model:
            editor_key: trim_bottom_right
            implied_boolean: true
            allowed_values:
              - '-'
            optional: true
            default: '-'
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
  _cc_jekyll_unknown_tag:
    hidden: true
    snippet: '{%[[trim_left]] [[name]][[args]] [[trim_right]]%}'
    preview:
      text: Unknown Shortcode
      subtext:
        - key: name
      icon: question_mark
    _inputs:
      name:
        type: auto
        hidden: true
        cascade: true
      args:
        type: auto
        hidden: true
        cascade: true
      trim_left:
        type: auto
        hidden: true
        cascade: true
      trim_right:
        type: auto
        hidden: true
        cascade: true
    params:
      name:
        parser: argument
        options:
          model:
            editor_key: name
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
      args:
        parser: content
        options:
          editor_key: args
          raw: true
          allow_nested: false
      trim_left:
        parser: argument
        options:
          model:
            editor_key: trim_left
            implied_boolean: true
            allowed_values:
              - '-'
            optional: true
            default: '-'
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
      trim_right:
        parser: argument
        options:
          model:
            editor_key: trim_right
            implied_boolean: true
            allowed_values:
              - '-'
            optional: true
            default: '-'
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
  jekyll_highlight:
    inline: false
    template: jekyll_paired_tag_positional_args
    definitions:
      tag_name: highlight
      content_key: content
      positional_args:
        - editor_key: language
          type: string
          remove_empty: false
          optional: false
          implied_boolean: false
        - editor_key: linenos
          implied_boolean: true
          default: linenos
          allowed_values:
            - linenos
          optional: true
          remove_empty: false
    preview:
      text: Highlight
      subtext:
        - key: language
        - Code block with syntax highlighting.
      icon: code
    _inputs:
      content:
        type: code
        cascade: true
      language:
        type: select
        options:
          value_key: value
          text_key: name
          values:
            - value: abap
              name: SAP
            - value: actionscript
              name: Actionscript
            - value: apache
              name: Apache
            - value: apiblueprint
              name: API Blueprint
            - value: applescript
              name: AppleScript
            - value: awk
              name: AWK
            - value: biml
              name: BIML
            - value: brainfuck
              name: Brainfuck
            - value: bsl
              name: BSL
            - value: c
              name: C
            - value: ceylon
              name: Ceylon
            - value: cfscript
              name: CFScript
            - value: clojure
              name: Clojure
            - value: cmake
              name: CMake
            - value: coffeescript
              name: Coffeescript
            - value: common_lisp
              name: Common Lisp
            - value: conf
              name: config
            - value: console
              name: Console
            - value: coq
              name: Coq
            - value: cpp
              name: C++
            - value: crystal
              name: Crystal
            - value: csharp
              name: C#
            - value: css
              name: Cascading Style Sheets
            - value: d
              name: D
            - value: dart
              name: Dart
            - value: diff
              name: Diff
            - value: digdag
              name: DigDag
            - value: docker
              name: Docker
            - value: dot
              name: Dot
            - value: eiffel
              name: Eiffel
            - value: elixir
              name: Elixir
            - value: elm
              name: Elm
            - value: erb
              name: Embedded ruby template files
            - value: erlang
              name: Erlang
            - value: escape
              name: Escape
            - value: factor
              name: Factor
            - value: fortran
              name: Fortran
            - value: fsharp
              name: F#
            - value: gherkin
              name: Gerkin
            - value: glsl
              name: GLSL
            - value: go
              name: Go
            - value: gradle
              name: Gradle
            - value: graphql
              name: GraphQL
            - value: groovy
              name: Groovy
            - value: hack
              name: Hack
            - value: haml
              name: Haml
            - value: handlebars
              name: Handlebars
            - value: haskell
              name: Haskell
            - value: hcl
              name: Hasicorp Configuration Language
            - value: html
              name: HTML
            - value: http
              name: http
            - value: hylang
              name: HyLang
            - value: idlang
              name: Interactive Data Language
            - value: igorpro
              name: WaveMetrics Igor Pro
            - value: ini
              name: INI
            - value: io
              name: IO
            - value: irb
              name: IRB
            - value: java
              name: Java
            - value: javascript
              name: JavaScript
            - value: jinja
              name: Jinja
            - value: json
              name: JSON
            - value: json
              name: JSON Doc
            - value: jsonnet
              name: JSON net
            - value: jsp
              name: JSP
            - value: jsx
              name: JSX
            - value: julia
              name: Julia
            - value: kotlin
              name: Kotlin
            - value: lasso
              name: Lasso
            - value: liquid
              name: Liquid
            - value: literate_coffeescript
              name: Literate CoffeeScript
            - value: literate_haskell
              name: Literate Haskell
            - value: llvm
              name: LLVM
            - value: lua
              name: Lua
            - value: m68k
              name: Motorola 68k Assembler
            - value: magik
              name: Smallworld Majik
            - value: make
              name: Makefile
            - value: markdown
              name: Markdown
            - value: mathematica
              name: Wolfram Mathmatica
            - value: matlab
              name: Matlab
            - value: moonscript
              name: Moonscript
            - value: mosel
              name: Mosel
            - value: mxml
              name: MXML
            - value: nasm
              name: Netwide Assembler
            - value: nginx
              name: Nginx configuration file
            - value: nim
              name: Nim
            - value: nix
              name: Nix
            - value: objective_c
              name: Objective-C
            - value: ocaml
              name: OCaml
            - value: pascal
              name: Pascal
            - value: perl
              name: Perl
            - value: php
              name: PHP
            - value: plaintext
              name: Plaintext
            - value: plist
              name: plist
            - value: powershell
              name: Powershell
            - value: praat
              name: Praat
            - value: prolog
              name: Prolog
            - value: prometheus
              name: Prometheus
            - value: properties
              name: Properties
            - value: protobuf
              name: Protocol Buffer
            - value: puppet
              name: Puppet
            - value: python
              name: Python
            - value: q
              name: Q
            - value: qml
              name: QML
            - value: r
              name: R
            - value: racket
              name: Racket
            - value: ruby
              name: Ruby
            - value: rust
              name: Rust
            - value: sass
              name: Sass
            - value: scala
              name: Scala
            - value: scheme
              name: Scheme
            - value: scss
              name: SCSS
            - value: sed
              name: sed
            - value: shell
              name: Shell
            - value: sieve
              name: Sieve
            - value: slim
              name: Slim
            - value: smalltalk
              name: Smalltalk
            - value: smarty
              name: Smarty
            - value: sml
              name: Standard ML
            - value: sqf
              name: Status Quo Function
            - value: sql
              name: Structured Query Language
            - value: supercollider
              name: Supercollider
            - value: swift
              name: Swift
            - value: tap
              name: TAP
            - value: tcl
              name: TCL
            - value: terraform
              name: Terraform
            - value: tex
              name: TeX
            - value: toml
              name: TOML
            - value: tsx
              name: tsx
            - value: tulip
              name: Tulip
            - value: turtle
              name: Turtle
            - value: twig
              name: Twig
            - value: typescript
              name: TypeScript
            - value: vala
              name: vala
            - value: vb
              name: Visual Basic
            - value: verilog
              name: Verilog
            - value: vhdl
              name: VHDL
            - value: viml
              name: VimL
            - value: vue
              name: Vue
            - value: wollok
              name: Wollok
            - value: xml
              name: XML
            - value: xojo
              name: Xojo
            - value: yaml
              name: Yaml
        cascade: true
  _cc_jekyll_template:
    hidden: true
    snippet: '{{[[trim_left]][[template]][[trim_right]]}}'
    preview:
      text: Template
      subtext:
        - key: template
      icon: code
    _inputs:
      template:
        type: auto
        hidden: true
        cascade: true
      trim_left:
        type: auto
        hidden: true
        cascade: true
      trim_right:
        type: auto
        hidden: true
        cascade: true
    params:
      template:
        parser: content
        options:
          editor_key: template
          raw: true
          allow_nested: false
          forbidden_tokens:
            - '{{'
            - '{{-'
      trim_left:
        parser: argument
        options:
          model:
            editor_key: trim_left
            implied_boolean: true
            allowed_values:
              - '-'
            optional: true
            default: '-'
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '}}'
      trim_right:
        parser: argument
        options:
          model:
            editor_key: trim_right
            implied_boolean: true
            allowed_values:
              - '-'
            optional: true
            default: '-'
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '}}'
  jekyll_raw:
    snippet: >-
      {%[[trim_top_left]] raw
      [[trim_top_right]]%}[[content]]{%[[trim_bottom_left]] endraw
      [[trim_bottom_right]]%}
    preview:
      text: Raw
      icon: data_object
    picker_preview:
      subtext: Outputs Jekyll tags as plain text.
    params:
      content:
        parser: content
        options:
          editor_key: content
          allow_nested: false
          raw: true
      trim_top_left:
        parser: argument
        options:
          model:
            editor_key: trim_top_left
            implied_boolean: true
            allowed_values:
              - '-'
            default: '-'
            optional: true
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
      trim_top_right:
        parser: argument
        options:
          model:
            editor_key: trim_top_right
            implied_boolean: true
            allowed_values:
              - '-'
            optional: true
            default: '-'
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
      trim_bottom_left:
        parser: argument
        options:
          model:
            editor_key: trim_bottom_left
            implied_boolean: true
            allowed_values:
              - '-'
            optional: true
            default: '-'
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
      trim_bottom_right:
        parser: argument
        options:
          model:
            editor_key: trim_bottom_right
            implied_boolean: true
            allowed_values:
              - '-'
            optional: true
            default: '-'
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'
    _inputs:
      content:
        type: code
        cascade: true
  jekyll_link:
    template: jekyll_tag_positional_args
    definitions:
      tag_name: link
      positional_args:
        - editor_key: path
          type: string
          remove_empty: false
          optional: false
          implied_boolean: false
    preview:
      text: Link
      subtext:
        - key: path
        - Links to the specified URL or path.
      icon: link
      view: inline
    _inputs:
      path:
        type: url
        comment: Enter the URL or path to link to.
        cascade: true
        text: Link
  jekyll_post_url:
    template: jekyll_tag_positional_args
    definitions:
      tag_name: post_url
      positional_args:
        - editor_key: post
          type: string
          remove_empty: false
          optional: false
          implied_boolean: false
    preview:
      text: Post URL
      subtext:
        - key: post
        - Outputs the URL of the specified blog post.
      icon: link
      view: inline
    _inputs:
      post:
        type: url
        comment: Enter the post name or path.
        cascade: true
        text: Post
editor:
  default_path:
timezone: America/New_York
