_schema: _schema
paths:
  uploads: uploads
  static: ''
collections_config:
  posts:
    path: _posts
    name: Posts
    icon: event_available
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.posts[*].tags
        cascade: true
    add_options:
      - name: Add Post
      - name: Add Draft
        collection: drafts
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  organizers:
    path: _organizers
    name: Organizers
    icon: equalizer
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: _data
    name: Data
    icon: data_usage
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
  drafts:
    path: _drafts
    name: Drafts
    icon: event
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.posts[*].tags
        cascade: true
    create:
      path: ''
      publish_to: posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  event-instructions:
    path: _event-instructions
    name: Event Instructions
    icon: construction
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  speakers:
    path: _speakers
    name: Speakers
    icon: speaker
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  events:
    path: _events
    name: Events
    icon: event
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  tracks:
    path: _tracks
    name: Tracks
    icon: stacks
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_snippets_imports:
  jekyll: true
timezone: America/New_York
markdown:
  engine: kramdown
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
