_schema: _schema
source: /
paths:
  uploads: uploads
  static: ''
collections_config:
  sponsors:
   path: _sponsors
  home:
   path: _includes/2026-home.html  
  posts:
    path: _posts
    name: Posts
    icon: event_available
    disable_url: false
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.posts[*].tags
        cascade: true
    add_options:
      - name: Add Post
        schema: default  
      - name: Embed Social
        schema: social
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/post-article.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Article
        icon: notes
      social:
        path: .cloudcannon/schemas/embedded-posts.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: Embedded Social Post
        icon: notes
  organizers:
    path: _organizers
    name: Organizers
    icon: equalizer
    disable_url: false
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
  data:
    path: _data
    name: Data
    icon: data_usage
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
collection_groups:
  - heading: Current News
    collections:
      - posts
  - heading: Home Page
    collections:
      - sponsors
      - brand
      - home
_snippets_imports:
  jekyll: true
timezone: America/New_York
markdown:
  engine: kramdown
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
